# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_cbv', '0003_auto_20180112_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
