# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_slug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
