# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_slug', '0002_auto_20180112_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(),
        ),
    ]
